# billing-engine/Dockerfile
FROM bitnami/spark:3.4.1

# Téléchargement direct depuis le repo PostgreSQL
ADD https://jdbc.postgresql.org/download/postgresql-42.6.0.jar /opt/bitnami/spark/jars/

WORKDIR /app
COPY billing_engine.py .

CMD ["/opt/bitnami/spark/bin/spark-submit", "billing_engine.py"]




